[package]
name = "utransport-mock"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.41.0", features = ["bitflags", "async"] }
up-core-api-wit = { path = "../up-core-api-wit" }
